spring.application.name=AuthService
server.port=8999
eureka.instance.hostname=localhost

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5433/authDB
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=root

pv.app.jwtCookieName= token
pv.app.jwtRefreshCookieName= pv-jwt-refresh
pv.app.jwtSecret= 7A69344E6858775472387931502F4C6251656D694D794D354C35447066794F7536
#pv.app.jwtExpirationMs= 86400000
#pv.app.jwtRefreshExpirationMs= 86400000

pv.app.jwtExpirationMs= 7776000000
pv.app.jwtRefreshExpirationMs= 7776000000
front.end=http://localhost:3000

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
